export const GET_OWNER = 'getOwner'
export const GET_FRIENDS = 'getFriends'
export const GET_TOP_WORDS = 'getTopWords'
export const GET_TOP_EMOJIS = 'getTopEmojis'
export const GET_TOP_PARTICIPANTS = 'getTopParticipants'
export const GET_PARTICIPANTS = 'getParticipants'
export const GET_STATUS = 'getStatus'
export const GET_TOTAL_WORDS = 'getTotalWords'
export const GET_TOTAL_MESSAGES = 'getTotalMessages'
export const GET_TOTAL_CONVERSATION = 'getTotalConversation'
export const GET_TIMING = 'getTiming'
export const GET_WORDS = 'getWords'

